stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/Sport car price.csv
      - src/preprocessing.py
    params:
      - preprocessing.input_path
      - preprocessing.output_train_path
      - preprocessing.output_test_path
      - preprocessing.output_pipeline_path
      - preprocessing.test_size
      - preprocessing.random_state
    outs:
      - data/processed_train_data.csv
      - data/processed_test_data.csv
      - data/pipeline.pkl